Repository CollapseLauncher/Collapse, pull requests merged in 2023-08, with the labels that each got.

#218 WinAppSDK NuGet update to 1.3.230724000
  CollapseLauncher/Classes/GameManagement/GameSettings/BaseClass/SettingsBase.cs
  CollapseLauncher/CollapseLauncher.csproj
  CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
  CollapseLauncher/packages.lock.json
  Hi3Helper.Core/packages.lock.json
Labels: Enhancement, Area: Runtime

#222 Rewrite GameUninstall Method
  CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs
  CollapseLauncher/Classes/InstallManagement/Genshin/GenshinInstall.cs
  CollapseLauncher/Classes/InstallManagement/Honkai/HonkaiInstall.cs
  CollapseLauncher/Classes/InstallManagement/StarRail/StarRailInstall.cs
Labels: Enhancement, Area: Runtime

#220 Build version indicator
  CollapseLauncher/XAMLs/MainApp/MainPage.xaml
  CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs
  CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
Labels: Enhancement, Area: UI/UX

#230 Fix preload version issues
  CollapseLauncher/Classes/GameManagement/GameVersion/BaseClass/GameVersionBase.cs
  CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml
  CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
Labels: Bug, Area: Preset Config, Game: Genshin Impact, Game: Honkai Impact 3rd

#231 Genshin Game Settings update
  CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/Enums/Enums.cs
  CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GeneralData.cs
  CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GlobalPerfData.cs
  CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GraphicsData.cs
  CollapseLauncher/Classes/GameManagement/GameVersion/BaseClass/GameVersionBase.cs
  CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs
  CollapseLauncher/Classes/Interfaces/Class/ProgressBase.cs
  CollapseLauncher/Classes/RepairManagement/Genshin/Check.cs
  CollapseLauncher/Classes/RepairManagement/Genshin/Fetch.cs
  CollapseLauncher/Classes/RepairManagement/Genshin/GenshinRepair.cs
  CollapseLauncher/CollapseLauncher.csproj
  CollapseLauncher/XAMLs/MainApp/Pages/Dialogs/SimpleDialogs.cs
  CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.Ext.cs
  CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml
  CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
  Hi3Helper.Core/Lang/Locale/LangGenshinGameSettingsPage.cs
  Hi3Helper.Core/Lang/en-us.json
  README.md
Labels: Enhancement, Game: Genshin Impact
