Repository CollapseLauncher/Collapse, pull requests merged in 2023-12, with the labels that each got.

#317 Run Collapse after login using Task Scheduler
  CollapseLauncher/CollapseLauncher.csproj
  CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml
  CollapseLauncher/XAMLs/MainApp/Pages/SettingsPage.xaml.cs
  CollapseLauncher/packages.lock.json
  Hi3Helper.Core/Lang/Locale/LangSettingsPage.cs
  Hi3Helper.Core/Lang/en_US.json
Labels: Enhancement, Area: UI/UX

#327 Update & Improve th-TH translation
  Hi3Helper.Core/Lang/th_TH.json
Labels: Translation Completed

#303 French translation of README.md
  README.fr-fr.md
  README.id-id.md
  README.ja-jp.md
  README.md
  README.pt-pt.md
Labels: Area: Translation, Area: Wiki

#343 Dispose the stream before deleting install package
  CollapseLauncher/Classes/InstallManagement/BaseClass/InstallManagerBase.cs
Labels: Bug
