Repository CollapseLauncher/Collapse, pull requests merged in 2024-02, with the labels that each got.

#388 Support GI `Dynamic Character Resolution`
  CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/Enums/Enums.cs
  CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GlobalPerfData.cs
  CollapseLauncher/Classes/GameManagement/GameSettings/Genshin/RegistryClass/GraphicsData.cs
  CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.Ext.cs
  CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml
  Hi3Helper.Core/Lang/Locale/LangGenshinGameSettingsPage.cs
  Hi3Helper.Core/Lang/en_US.json
Labels: Game: Genshin Impact, Area: UI/UX, Area: Game Settings

#392 Recalculate non-client area size after changing window size
  CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs
  CollapseLauncher/XAMLs/MainApp/MainWindow.xaml.cs
  CollapseLauncher/XAMLs/StartUp/StartupLanguageSelect.xaml.cs
Labels: Bug, Area: UI/UX

#393 (Discord RPC) Catch SEHException on Dispose
  Hi3Helper.Core/Classes/DiscordPresence/src/Core.cs
Labels: Area: Runtime

#398 [Feature] Pre-Launch and Post-Exit Commands Launching
  CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/RegistryClass/Model.cs
  CollapseLauncher/Classes/GameManagement/GameSettings/StarRail/Settings.cs
  CollapseLauncher/Classes/GameManagement/GameSettings/Universal/RegistryClass/CollapseMiscSetting.cs
  CollapseLauncher/CollapseLauncher.csproj
  CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs
  CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPage.xaml
  CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/GenshinGameSettingsPage.Ext.cs
  CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/GenshinGameSettingsPage.xaml
  CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/GenshinGameSettingsPage.xaml.cs
  CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/HonkaiGameSettingsPage.Ext.cs
  CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/HonkaiGameSettingsPage.xaml
  CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/HonkaiGameSettingsPage.xaml.cs
  CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/StarRailGameSettingsPage.Ext.cs
  CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/StarRailGameSettingsPage.xaml
  CollapseLauncher/XAMLs/MainApp/Pages/GameSettingsPages/StarRailGameSettingsPage.xaml.cs
  CollapseLauncher/XAMLs/MainApp/Pages/GenshinGameSettingsPage.xaml
  CollapseLauncher/XAMLs/MainApp/Pages/HomePage.xaml.cs
  CollapseLauncher/XAMLs/MainApp/Pages/StarRailGameSettingsPage.xaml
  CollapseLauncher/packages.lock.json
  Hi3Helper.Core/Classes/Logger/Enum/LogType.cs
  Hi3Helper.Core/Classes/Logger/LoggerBase.cs
  Hi3Helper.Core/Lang/Locale/LangGameSettingsPage.cs
  Hi3Helper.Core/Lang/Locale/LangStarRailGameSettingsPage.cs
  Hi3Helper.Core/Lang/en_US.json
  Hi3Helper.Core/packages.lock.json
Labels: Enhancement, Area: Game Settings

#403 [URL Protocol] Fix Discord Rich Presence not updating.
  CollapseLauncher/XAMLs/MainApp/MainPage.xaml.cs
Labels: Bug
